feat(said): add migration process

diff --git a/packages/server/Dockerfile b/packages/server/Dockerfile
--- a/packages/server/Dockerfile
+++ b/packages/server/Dockerfile
@@ -18,10 +18,12 @@ RUN npm i -g pnpm@${PNPM_VERSION}
 COPY --from=deps /repo /repo
 COPY . .
 
-RUN pnpm --filter "./packages/server" exec prisma generate
+RUN node packages/server/scripts/merge-prisma-models.js
+RUN pnpm --filter "./packages/server" exec prisma generate --schema ./prisma/schema.prisma
+
 RUN pnpm --filter "./packages/server" build
 
-# 3) prod deps (server only)
+# 3) prod deps 
 FROM node:lts-alpine AS prod_deps
 WORKDIR /repo
 ENV NODE_ENV=production
@@ -30,15 +32,16 @@ RUN npm i -g pnpm@${PNPM_VERSION}
 COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
 COPY packages/server/package.json packages/server/package.json
 COPY packages/server/prisma packages/server/prisma
+COPY packages/server/scripts packages/server/scripts
 
-RUN pnpm --filter "./packages/server..."  install --frozen-lockfile --ignore-scripts
-RUN pnpm --filter "./packages/server" exec prisma generate
+RUN pnpm --filter "./packages/server..." install --frozen-lockfile --ignore-scripts
 
-# 4) runtime (run from package root)
+RUN node packages/server/scripts/merge-prisma-models.js
+RUN pnpm --filter "./packages/server" exec prisma generate --schema ./prisma/schema.prisma
+
+# 4) runtime
 FROM node:lts-alpine AS runner
 ENV NODE_ENV=production
-
-
 WORKDIR /app/packages/server
 
 COPY --from=prod_deps /repo/packages/server/node_modules ./node_modules
@@ -52,4 +55,14 @@ COPY --from=build /repo/packages/server/package.json ./package.json
 COPY --from=build /repo/packages/server/scripts ./scripts
 
 EXPOSE 3000
-CMD ["node", "dist/src/main.js"]
+
+CMD ["sh", "-lc", "\
+  set -e; \
+  if [ -z \"${DATABASE_URL:-}\" ]; then \
+    echo 'ERROR: DATABASE_URL is empty (missing env).'; exit 1; \
+  fi; \
+  node scripts/merge-prisma-models.js; \
+  npx prisma generate --schema ./prisma/schema.prisma; \
+  npx prisma db push --schema ./prisma/schema.prisma --url \"$DATABASE_URL\"; \
+  exec node dist/src/main.js \
+"]
